In [ ]:
%tensorflow_version 2.x
import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

Found GPU at: /device:GPU:0


In [ ]:
%tensorflow_version 2.x
import tensorflow as tf
import timeit

device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  print(
      '\n\nThis error most likely means that this notebook is not '
      'configured to use a GPU.  Change this in Notebook Settings via the '
      'command palette (cmd/ctrl-shift-P) or the Edit menu.\n\n')
  raise SystemError('GPU device not found')

def cpu():
  with tf.device('/cpu:0'):
    random_image_cpu = tf.random.normal((100, 100, 100, 3))
    net_cpu = tf.keras.layers.Conv2D(32, 7)(random_image_cpu)
    return tf.math.reduce_sum(net_cpu)

def gpu():
  with tf.device('/device:GPU:0'):
    random_image_gpu = tf.random.normal((100, 100, 100, 3))
    net_gpu = tf.keras.layers.Conv2D(32, 7)(random_image_gpu)
    return tf.math.reduce_sum(net_gpu)

# We run each op once to warm up; see: https://stackoverflow.com/a/45067900
cpu()
gpu()

# Run the op several times.
print('Time (s) to convolve 32x7x7x3 filter over random 100x100x100x3 images '
      '(batch x height x width x channel). Sum of ten runs.')
print('CPU (s):')
cpu_time = timeit.timeit('cpu()', number=10, setup="from __main__ import cpu")
print(cpu_time)
print('GPU (s):')
gpu_time = timeit.timeit('gpu()', number=10, setup="from __main__ import gpu")
print(gpu_time)
print('GPU speedup over CPU: {}x'.format(int(cpu_time/gpu_time)))

Time (s) to convolve 32x7x7x3 filter over random 100x100x100x3 images (batch x height x width x channel). Sum of ten runs.
CPU (s):
3.6170942800000034
GPU (s):
0.048118093000027784
GPU speedup over CPU: 75x


In [ ]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [ ]:
# Initialization
x = tf.constant(4, shape=(1, 1), dtype=tf.float32)
print(x)

x = tf.constant([[1, 2, 3], [4, 5, 6]], shape=(2, 3))
print(x)

x = tf.eye(3)
print(x)

x = tf.ones((4, 3))
print(x)

x = tf.zeros((3, 2, 5))
print(x)

x = tf.random.uniform((2, 2), minval=0, maxval=1)
print(x)

x = tf.random.normal((3, 3), mean=0, stddev=1)
print(tf.cast(x, dtype=tf.float64))
# tf.float (16,32,64), tf.int (8, 16, 32, 64), tf.bool

x = tf.range(9)
x = tf.range(start=0, limit=10, delta=2)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(4, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 2, 5), dtype=float32)
tf.Tensor(
[[0.0540899  0.7809763 ]
 [0.7347256  0.12115991]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0.56623864 -0.99144644 -0.84927344]
 [-0.23078705 -0.07150687  0.25640845]
 [ 0.90426153  1.27145088  0.42763475]], shape=(3, 3), dtype=float64)
tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)


In [ ]:
# Math

#element-wise operations
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])

z = tf.add(x, y)
z = x + y
print(z)

z = tf.subtract(x, y)
z = x - y
print(z)

z = tf.divide(x, y)
z = x / y
print(z)

z = tf.multiply(x, y)
z = x * y
print(z)


#element-wise multiplication and then summation
z = tf.tensordot(x, y, axes=1)
z = tf.reduce_sum(x*y, axis=0)
print(z)


z = x ** 5
print(z)


x = tf.random.normal((2, 3))
y = tf.random.normal((3, 2))
z = tf.matmul(x, y)
z = x @ y
print(z)

x = tf.random.normal((2, 2))

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)
tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)
tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)
tf.Tensor(46, shape=(), dtype=int32)
tf.Tensor([  1  32 243], shape=(3,), dtype=int32)
tf.Tensor(
[[ 2.063076   -0.44910747]
 [ 2.2348473  -1.0109867 ]], shape=(2, 2), dtype=float32)


In [ ]:
# Indexing
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2])
print(x[::-1])

indices = tf.constant([0, 3])
x_indices = tf.gather(x, indices)
print(x_indices)

x = tf.constant([[1, 2], [3, 4], [5, 6]])

print(x[0, :])
print(x[0:2, :])


tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)
tf.Tensor([0 2], shape=(2,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [ ]:
# Reshaping
x = tf.range(9)
print(x)

x = tf.reshape(x, (3, 3))
print(x)

x = tf.transpose(x, perm=[1, 0])
print(x)

x = tf.transpose(x, perm=[1, 0])
print(x)

x = tf.random.normal((5,5,3))
x = tf.reshape(x, [-1,])
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[-1.3083701   0.5643746  -1.4199505  -0.47139707 -1.0932127  -0.6521097
  0.8161861  -0.9095208   0.21995175 -1.1006311  -2.7728727  -0.5768039
 -2.7716784  -1.2200434  -0.47228888  0.06409699  1.5177748  -0.08468293
  1.6347823   1.263455    1.2362937   1.7652506   0.516708   -0.78091156
 -1.9266231   1.1274539  -0.38541353 -0.13980883 -0.30654633 -1.5262358
  0.06801758 -0.01412568 -0.65526384  0.2340061  -0.08360461  1.2987269
 -0.28258526 -1.0690365   0.20892313  3.3006997   0.06374627  0.80080545
  0.8203447   0.1281679  -1.0913788  -0.9171942   0.553912   -0.21799463
  1.768779   -0.26310885 -1.022221   -0.8987734   0.30104688  1.0012401
  1.2380235   0.07277723 -0.08580884 -0.46358502 -1.3307132   0.48800862
 -0.996

In [ ]:
# np.array(tf.range(9)).reshape(-1,1)

# Neural Networks with Sequential and Functional API

In [ ]:
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist



(x_train, y_train), (x_test, y_test) = mnist.load_data()
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

x_train = x_train.reshape(-1, 28 * 28).astype("float32") / 255.0
x_test = x_test.reshape(-1, 28 * 28).astype("float32") / 255.0

print(x_train.shape)
print(x_test.shape)

11501568/11490434 [==============================] - 0s 0us/step
(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)
(60000, 784)
(10000, 784)


In [ ]:
# Sequential API (Very convenient, not very flexible)
model = keras.Sequential(
    [
        keras.Input(shape=(28 * 28)),
        layers.Dense(512, activation="relu"),
        layers.Dense(256, activation="relu"),
        layers.Dense(10),
    ]
)
print(model.summary())
model.compile(
    #our last layer doesnot implement softmax so we set logits=True
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(lr=0.001),
    metrics=["accuracy"],
)

model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=2)
model.evaluate(x_test, y_test, batch_size=32, verbose=2)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 512)               401920    
                                                                 
 dense_1 (Dense)             (None, 256)               131328    
                                                                 
 dense_2 (Dense)             (None, 10)                2570      
                                                                 
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________
None


/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


Epoch 1/5
1875/1875 - 5s - loss: 0.1842 - accuracy: 0.9437 - 5s/epoch - 3ms/step
Epoch 2/5
1875/1875 - 4s - loss: 0.0786 - accuracy: 0.9749 - 4s/epoch - 2ms/step
Epoch 3/5
1875/1875 - 5s - loss: 0.0554 - accuracy: 0.9826 - 5s/epoch - 2ms/step
Epoch 4/5
1875/1875 - 7s - loss: 0.0431 - accuracy: 0.9860 - 7s/epoch - 4ms/step
Epoch 5/5
1875/1875 - 7s - loss: 0.0328 - accuracy: 0.9891 - 7s/epoch - 4ms/step
313/313 - 1s - loss: 0.0982 - accuracy: 0.9743 - 1s/epoch - 5ms/step


[0.09817493706941605, 0.9743000268936157]

In [ ]:
#Another way of implementing Sequential API
model = keras.Sequential()
model.add(keras.Input(shape=(784)))
model.add(layers.Dense(512, activation="relu"))
model.add(layers.Dense(256, activation="relu", name="my_layer"))
model.add(layers.Dense(10))


print(model.summary())
model.compile(
    #our last layer doesnot implement softmax so we set logits=True
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(lr=0.001),
    metrics=["accuracy"],
)

model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=2)
print("*************")
model.evaluate(x_test, y_test, batch_size=32, verbose=2)

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 512)               401920    
                                                                 
 my_layer (Dense)            (None, 256)               131328    
                                                                 
 dense_4 (Dense)             (None, 10)                2570      
                                                                 
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________
None


/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


Epoch 1/5
1875/1875 - 8s - loss: 0.1859 - accuracy: 0.9429 - 8s/epoch - 4ms/step
Epoch 2/5
1875/1875 - 7s - loss: 0.0807 - accuracy: 0.9745 - 7s/epoch - 4ms/step
Epoch 3/5
1875/1875 - 6s - loss: 0.0536 - accuracy: 0.9829 - 6s/epoch - 3ms/step
Epoch 4/5
1875/1875 - 6s - loss: 0.0424 - accuracy: 0.9859 - 6s/epoch - 3ms/step
Epoch 5/5
1875/1875 - 7s - loss: 0.0316 - accuracy: 0.9900 - 7s/epoch - 4ms/step
*************
313/313 - 1s - loss: 0.0834 - accuracy: 0.9790 - 920ms/epoch - 3ms/step


[0.08336592465639114, 0.9789999723434448]

In [ ]:
# Functional API (A bit more flexible)
# with ADAM Optimizer

inputs = keras.Input(shape=(784))
x1 = layers.Dense(512, activation="relu", name="first_layer")(inputs)
x2 = layers.Dense(256, activation="relu", name="second_layer")(x1)
outputs = layers.Dense(10, activation="softmax")(x2)
model = keras.Model(inputs=inputs, outputs=outputs)

print(model.summary())

model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    optimizer=keras.optimizers.Adam(lr=0.001),
    metrics=["accuracy"],
)

model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=2)
model.evaluate(x_test, y_test, batch_size=32, verbose=2)

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_3 (InputLayer)        [(None, 784)]             0         
                                                                 
 first_layer (Dense)         (None, 512)               401920    
                                                                 
 second_layer (Dense)        (None, 256)               131328    
                                                                 
 dense_5 (Dense)             (None, 10)                2570      
                                                                 
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/5


/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


1875/1875 - 5s - loss: 0.1832 - accuracy: 0.9443 - 5s/epoch - 3ms/step
Epoch 2/5
1875/1875 - 4s - loss: 0.0814 - accuracy: 0.9750 - 4s/epoch - 2ms/step
Epoch 3/5
1875/1875 - 4s - loss: 0.0546 - accuracy: 0.9829 - 4s/epoch - 2ms/step
Epoch 4/5
1875/1875 - 4s - loss: 0.0402 - accuracy: 0.9869 - 4s/epoch - 2ms/step
Epoch 5/5
1875/1875 - 4s - loss: 0.0338 - accuracy: 0.9890 - 4s/epoch - 2ms/step
313/313 - 1s - loss: 0.0813 - accuracy: 0.9795 - 856ms/epoch - 3ms/step


[0.08131862431764603, 0.9794999957084656]

In [ ]:
#with SGD optimizer
inputs = keras.Input(shape=(784))
x = layers.Dense(512, activation="relu", name="first_layer")(inputs)
x = layers.Dense(256, activation="relu", name="second_layer")(x)
outputs = layers.Dense(10, activation="softmax")(x)
model = keras.Model(inputs=inputs, outputs=outputs)

print(model.summary())

model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    optimizer=keras.optimizers.SGD(learning_rate=0.001, momentum=0.0, nesterov=False, name="SGD"),
    metrics=["accuracy"],
)

model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=2)
model.evaluate(x_test, y_test, batch_size=32, verbose=2)

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_4 (InputLayer)        [(None, 784)]             0         
                                                                 
 first_layer (Dense)         (None, 512)               401920    
                                                                 
 second_layer (Dense)        (None, 256)               131328    
                                                                 
 dense_6 (Dense)             (None, 10)                2570      
                                                                 
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/5
1875/1875 - 4s - loss: 1.6357 - accuracy: 0.6284 - 4s/epoch - 2ms/step
Epoch 2/5
1875/1875 - 4s - loss: 0.7830 - accuracy: 0.8334 - 4s/epoch - 2ms/step
Epoch 3/5
1875/187

[0.3680301904678345, 0.9002000093460083]

In [ ]:
# RMSProp
inputs = keras.Input(shape=(784))
x = layers.Dense(512, activation="relu", name="first_layer")(inputs)
x = layers.Dense(256, activation="relu", name="second_layer")(x)
outputs = layers.Dense(10, activation="softmax")(x)
model = keras.Model(inputs=inputs, outputs=outputs)

print(model.summary())

model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    optimizer=keras.optimizers.RMSprop(
    learning_rate=0.001,
    rho=0.9,
    momentum=0.0,
    epsilon=1e-07,
    centered=False,
    name="RMSprop",
    ),
    metrics=["accuracy"],
)

model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=2)
model.evaluate(x_test, y_test, batch_size=32, verbose=2)

Model: "model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_5 (InputLayer)        [(None, 784)]             0         
                                                                 
 first_layer (Dense)         (None, 512)               401920    
                                                                 
 second_layer (Dense)        (None, 256)               131328    
                                                                 
 dense_7 (Dense)             (None, 10)                2570      
                                                                 
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/5
1875/1875 - 8s - loss: 0.1874 - accuracy: 0.9447 - 8s/epoch - 4ms/step
Epoch 2/5
1875/1875 - 6s - loss: 0.0957 - accuracy: 0.9742 - 6s/epoch - 3ms/step
Epoch 3/5
1875/187

[0.12462718784809113, 0.9769999980926514]

In [ ]:
# Functional API with ADAgrad
#Adagrad
inputs = keras.Input(shape=(784))
x = layers.Dense(512, activation="relu", name="first_layer")(inputs)
x = layers.Dense(256, activation="relu", name="second_layer")(x)
outputs = layers.Dense(10, activation="softmax")(x)
model = keras.Model(inputs=inputs, outputs=outputs)

print(model.summary())

model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    optimizer=keras.optimizers.Adagrad(
    learning_rate=0.001,
    initial_accumulator_value=0.1,
    epsilon=1e-07,
    name="Adagrad",
),
    metrics=["accuracy"],
)

model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=2)
model.evaluate(x_test, y_test, batch_size=32, verbose=2)

Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_6 (InputLayer)        [(None, 784)]             0         
                                                                 
 first_layer (Dense)         (None, 512)               401920    
                                                                 
 second_layer (Dense)        (None, 256)               131328    
                                                                 
 dense_8 (Dense)             (None, 10)                2570      
                                                                 
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/5
1875/1875 - 5s - loss: 1.0121 - accuracy: 0.7788 - 5s/epoch - 3ms/step
Epoch 2/5
1875/1875 - 4s - loss: 0.4404 - accuracy: 0.8868 - 4s/epoch - 2ms/step
Epoch 3/5
1875/187

[0.2776957154273987, 0.9222999811172485]

# CNN with Sequential and Functional API

In [ ]:
from tensorflow.keras.datasets import cifar10


(x_train, y_train), (x_test, y_test) = cifar10.load_data()

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

x_train = x_train.astype("float32") / 255.0
x_test = x_test.astype("float32") / 255.0

170508288/170498071 [==============================] - 2s 0us/step
(50000, 32, 32, 3)
(50000, 1)
(10000, 32, 32, 3)
(10000, 1)


In [ ]:
model = keras.Sequential(
    [
        keras.Input(shape=(32, 32, 3)),
        layers.Conv2D(32, (3,3), padding="valid", activation="relu"),
        layers.MaxPooling2D(),
        layers.Conv2D(64, (3,3), activation="relu"),
        layers.MaxPooling2D(),
        layers.Conv2D(64, (3,3), activation="relu"),
        layers.Flatten(),
        layers.Dense(64, activation="relu"),
        layers.Dense(10),
    ]
)
print(model.summary())
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    metrics=["accuracy"],
)

model.fit(x_train, y_train, batch_size=64, epochs=5, verbose=2)
model.evaluate(x_test, y_test, batch_size=64, verbose=2)

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_22 (Conv2D)          (None, 30, 30, 32)        896       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 15, 15, 32)       0         
 )                                                               
                                                                 
 conv2d_23 (Conv2D)          (None, 13, 13, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 6, 6, 64)         0         
 2D)                                                             
                                                                 
 conv2d_24 (Conv2D)          (None, 4, 4, 64)          36928     
                                                                 
 flatten (Flatten)           (None, 1024)             

[0.9275500774383545, 0.6819999814033508]

## CNN with Functional API and BatchNormalization

In [ ]:
def my_model():
    inputs = keras.Input(shape=(32, 32, 3))
    x = layers.Conv2D(32, 3)(inputs)
    x = layers.BatchNormalization()(x)
    x = keras.activations.relu(x)
    x = layers.MaxPooling2D()(x)

    x = layers.Conv2D(64, 3)(x)
    x = layers.BatchNormalization()(x)
    x = keras.activations.relu(x)
    x = layers.MaxPooling2D()(x)

    x = layers.Conv2D(128, 3)(x)
    x = layers.BatchNormalization()(x)
    x = keras.activations.relu(x)

    x = layers.Flatten()(x)

    x = layers.Dense(64, activation="relu")(x)
    outputs = layers.Dense(10)(x)
    model = keras.Model(inputs=inputs, outputs=outputs)
    return model


model = my_model()
print(model.summary())
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    metrics=["accuracy"],
)

model.fit(x_train, y_train, batch_size=64, epochs=5, verbose=2)
model.evaluate(x_test, y_test, batch_size=64, verbose=2)

Model: "model_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_8 (InputLayer)        [(None, 32, 32, 3)]       0         
                                                                 
 conv2d_25 (Conv2D)          (None, 30, 30, 32)        896       
                                                                 
 batch_normalization (BatchN  (None, 30, 30, 32)       128       
 ormalization)                                                   
                                                                 
 tf.nn.relu (TFOpLambda)     (None, 30, 30, 32)        0         
                                                                 
 max_pooling2d_2 (MaxPooling  (None, 15, 15, 32)       0         
 2D)                                                             
                                                                 
 conv2d_26 (Conv2D)          (None, 13, 13, 64)        1849

[1.039521336555481, 0.6650999784469604]

# Adding Regularization with L2 and Dropout

In [ ]:
from tensorflow.keras import layers, regularizers


(x_train, y_train), (x_test, y_test) = cifar10.load_data()
x_train = x_train.astype("float32") / 255.0
x_test = x_test.astype("float32") / 255.0


def my_model():
    inputs = keras.Input(shape=(32, 32, 3))
    x = layers.Conv2D(32, 3, padding="same", kernel_regularizer=regularizers.l2(0.01),)(
        inputs
    )
    x = layers.BatchNormalization()(x)
    x = keras.activations.relu(x)
    x = layers.MaxPooling2D()(x)
    x = layers.Conv2D(64, 3, padding="same", kernel_regularizer=regularizers.l2(0.01),)(
        x
    )
    x = layers.BatchNormalization()(x)
    x = keras.activations.relu(x)
    x = layers.MaxPooling2D()(x)
    x = layers.Conv2D(
        128, 3, padding="same", kernel_regularizer=regularizers.l2(0.01),
    )(x)
    x = layers.BatchNormalization()(x)
    x = keras.activations.relu(x)
    x = layers.Flatten()(x)
    x = layers.Dense(64, activation="relu", kernel_regularizer=regularizers.l2(0.01),)(
        x
    )
    x = layers.Dropout(0.5)(x)
    outputs = layers.Dense(10)(x)
    model = keras.Model(inputs=inputs, outputs=outputs)
    return model


model = my_model()
print(model.summary())
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(lr=3e-4),
    metrics=["accuracy"],
)

model.fit(x_train, y_train, batch_size=64, epochs=5, verbose=2)
model.evaluate(x_test, y_test, batch_size=64, verbose=2)

Model: "model_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_9 (InputLayer)        [(None, 32, 32, 3)]       0         
                                                                 
 conv2d_28 (Conv2D)          (None, 32, 32, 32)        896       
                                                                 
 batch_normalization_3 (Batc  (None, 32, 32, 32)       128       
 hNormalization)                                                 
                                                                 
 tf.nn.relu_3 (TFOpLambda)   (None, 32, 32, 32)        0         
                                                                 
 max_pooling2d_4 (MaxPooling  (None, 16, 16, 32)       0         
 2D)                                                             
                                                                 
 conv2d_29 (Conv2D)          (None, 16, 16, 64)        1849

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


Epoch 1/5
782/782 - 9s - loss: 3.0089 - accuracy: 0.3438 - 9s/epoch - 11ms/step
Epoch 2/5
782/782 - 8s - loss: 1.9293 - accuracy: 0.4534 - 8s/epoch - 10ms/step
Epoch 3/5
782/782 - 8s - loss: 1.6321 - accuracy: 0.5158 - 8s/epoch - 10ms/step
Epoch 4/5
782/782 - 8s - loss: 1.4986 - accuracy: 0.5496 - 8s/epoch - 10ms/step
Epoch 5/5
782/782 - 8s - loss: 1.4284 - accuracy: 0.5688 - 8s/epoch - 10ms/step
157/157 - 1s - loss: 1.2805 - accuracy: 0.6257 - 942ms/epoch - 6ms/step


[1.2804886102676392, 0.6256999969482422]

## RNNs, GRUs, LSTMs and Bidirectionality

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

x_train = x_train.reshape([-1, 28, 28]).astype("float32") / 255.0
x_test = x_test.reshape([-1, 28, 28]).astype("float32") / 255.0

print("*****")
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)
*****
(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)


## SimpleRNN

In [ ]:
model = keras.Sequential()
model.add(keras.Input(shape=(None, 28)))
model.add(layers.SimpleRNN(256, return_sequences=True, activation="relu"))
model.add(layers.SimpleRNN(256, activation="relu"))
model.add(layers.Dense(10))


print(model.summary())
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(lr=0.001),
    metrics=["accuracy"],
)

model.fit(x_train, y_train, batch_size=128, epochs=5, verbose=2)
model.evaluate(x_test, y_test, batch_size=64, verbose=2)

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_2 (SimpleRNN)    (None, None, 256)         72960     
                                                                 
 simple_rnn_3 (SimpleRNN)    (None, 256)               131328    
                                                                 
 dense_16 (Dense)            (None, 10)                2570      
                                                                 
Total params: 206,858
Trainable params: 206,858
Non-trainable params: 0
_________________________________________________________________
None


/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


Epoch 1/5
469/469 - 64s - loss: 0.3388 - accuracy: 0.8909 - 64s/epoch - 136ms/step
Epoch 2/5
469/469 - 46s - loss: 0.1122 - accuracy: 0.9670 - 46s/epoch - 98ms/step
Epoch 3/5
469/469 - 36s - loss: 0.0867 - accuracy: 0.9753 - 36s/epoch - 78ms/step
Epoch 4/5
469/469 - 36s - loss: 0.0717 - accuracy: 0.9800 - 36s/epoch - 78ms/step
Epoch 5/5
469/469 - 36s - loss: 0.0691 - accuracy: 0.9802 - 36s/epoch - 77ms/step
157/157 - 2s - loss: 0.0578 - accuracy: 0.9840 - 2s/epoch - 11ms/step


[0.057846441864967346, 0.984000027179718]

In [ ]:
# Default activation function for RNN is "tanh"

model = keras.Sequential()
model.add(keras.Input(shape=(None, 28)))
model.add(layers.SimpleRNN(256, return_sequences=True, activation="tanh"))
model.add(layers.SimpleRNN(256, activation="tanh"))
model.add(layers.Dense(10))


print(model.summary())
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(lr=0.001),
    metrics=["accuracy"],
)

model.fit(x_train, y_train, batch_size=64, epochs=5, verbose=2)
model.evaluate(x_test, y_test, batch_size=64, verbose=2)

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_4 (SimpleRNN)    (None, None, 256)         72960     
                                                                 
 simple_rnn_5 (SimpleRNN)    (None, 256)               131328    
                                                                 
 dense_17 (Dense)            (None, 10)                2570      
                                                                 
Total params: 206,858
Trainable params: 206,858
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/5


/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


Epoch 2/5
Epoch 3/5
Epoch 4/5
Epoch 5/5
157/157 - 2s - loss: 0.1370 - accuracy: 0.9612 - 2s/epoch - 11ms/step


[0.13700330257415771, 0.9611999988555908]

## RNN with GRU

In [ ]:
model = keras.Sequential()
model.add(keras.Input(shape=(None, 28)))
model.add(layers.GRU(256, return_sequences=True, activation="tanh"))
model.add(layers.GRU(256, activation="tanh"))
model.add(layers.Dense(10))


print(model.summary())
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(lr=0.001),
    metrics=["accuracy"],
)

model.fit(x_train, y_train, batch_size=64, epochs=5, verbose=2)
model.evaluate(x_test, y_test, batch_size=64, verbose=2)

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 gru (GRU)                   (None, None, 256)         219648    
                                                                 
 gru_1 (GRU)                 (None, 256)               394752    
                                                                 
 dense_18 (Dense)            (None, 10)                2570      
                                                                 
Total params: 616,970
Trainable params: 616,970
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/5


/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


938/938 - 136s - loss: 0.2891 - accuracy: 0.9030 - 136s/epoch - 145ms/step
Epoch 2/5
938/938 - 154s - loss: 0.0743 - accuracy: 0.9770 - 154s/epoch - 164ms/step
Epoch 3/5
938/938 - 106s - loss: 0.0495 - accuracy: 0.9853 - 106s/epoch - 113ms/step
Epoch 4/5
938/938 - 106s - loss: 0.0389 - accuracy: 0.9880 - 106s/epoch - 113ms/step
Epoch 5/5
938/938 - 107s - loss: 0.0318 - accuracy: 0.9902 - 107s/epoch - 114ms/step
157/157 - 3s - loss: 0.0446 - accuracy: 0.9860 - 3s/epoch - 16ms/step


[0.044587623327970505, 0.9860000014305115]

##RNN with LSTM

In [ ]:
model = keras.Sequential()
model.add(keras.Input(shape=(None, 28)))
model.add(layers.LSTM(256, return_sequences=True, activation="tanh"))
model.add(layers.LSTM(256, activation="tanh"))
model.add(layers.Dense(10))


print(model.summary())
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(lr=0.001),
    metrics=["accuracy"],
)

model.fit(x_train, y_train, batch_size=64, epochs=5, verbose=2)
model.evaluate(x_test, y_test, batch_size=64, verbose=2)

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, None, 256)         291840    
                                                                 
 lstm_1 (LSTM)               (None, 256)               525312    
                                                                 
 dense_19 (Dense)            (None, 10)                2570      
                                                                 
Total params: 819,722
Trainable params: 819,722
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/5


/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


938/938 - 22s - loss: 0.3037 - accuracy: 0.9005 - 22s/epoch - 24ms/step
Epoch 2/5
938/938 - 18s - loss: 0.0873 - accuracy: 0.9723 - 18s/epoch - 19ms/step
Epoch 3/5
938/938 - 18s - loss: 0.0591 - accuracy: 0.9818 - 18s/epoch - 19ms/step
Epoch 4/5
938/938 - 18s - loss: 0.0451 - accuracy: 0.9864 - 18s/epoch - 19ms/step
Epoch 5/5
938/938 - 18s - loss: 0.0382 - accuracy: 0.9879 - 18s/epoch - 19ms/step
157/157 - 2s - loss: 0.0608 - accuracy: 0.9822 - 2s/epoch - 15ms/step


[0.06082245334982872, 0.982200026512146]

## RNN with bidirectional layers on 1st LSTM layer

In [ ]:
model = keras.Sequential()
model.add(keras.Input(shape=(None, 28)))
model.add(
    layers.Bidirectional(layers.LSTM(256, return_sequences=True, activation="relu"))
)
model.add(layers.LSTM(256, name="lstm_layer2"))
model.add(layers.Dense(10))

print(model.summary())
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(lr=0.001),
    metrics=["accuracy"],
)

model.fit(x_train, y_train, batch_size=64, epochs=5, verbose=2)
model.evaluate(x_test, y_test, batch_size=64, verbose=2)

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 bidirectional (Bidirectiona  (None, None, 512)        583680    
 l)                                                              
                                                                 
 lstm_layer2 (LSTM)          (None, 256)               787456    
                                                                 
 dense_20 (Dense)            (None, 10)                2570      
                                                                 
Total params: 1,373,706
Trainable params: 1,373,706
Non-trainable params: 0
_________________________________________________________________
None


/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


Epoch 1/5
938/938 - 197s - loss: 0.2749 - accuracy: 0.9111 - 197s/epoch - 210ms/step
Epoch 2/5
938/938 - 161s - loss: 0.0848 - accuracy: 0.9742 - 161s/epoch - 172ms/step
Epoch 3/5
938/938 - 159s - loss: 0.0596 - accuracy: 0.9823 - 159s/epoch - 170ms/step
Epoch 4/5
938/938 - 159s - loss: 0.0485 - accuracy: 0.9852 - 159s/epoch - 170ms/step
Epoch 5/5
938/938 - 163s - loss: 0.0376 - accuracy: 0.9885 - 163s/epoch - 173ms/step
157/157 - 4s - loss: 0.0458 - accuracy: 0.9864 - 4s/epoch - 23ms/step


[0.04581201821565628, 0.9864000082015991]

## RNN with Bidirectional Layyer on both the LSTM Layers

In [ ]:
model = keras.Sequential()
model.add(keras.Input(shape=(None, 28)))
model.add(
    layers.Bidirectional(layers.LSTM(256, return_sequences=True, activation="relu"))
)
model.add(layers.Bidirectional(layers.LSTM(256, name="lstm_layer2")))
model.add(layers.Dense(10))

print(model.summary())
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(lr=0.001),
    metrics=["accuracy"],
)

model.fit(x_train, y_train, batch_size=64, epochs=10, verbose=2)
model.evaluate(x_test, y_test, batch_size=64, verbose=2)

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 bidirectional_1 (Bidirectio  (None, None, 512)        583680    
 nal)                                                            
                                                                 
 bidirectional_2 (Bidirectio  (None, 512)              1574912   
 nal)                                                            
                                                                 
 dense_21 (Dense)            (None, 10)                5130      
                                                                 
Total params: 2,163,722
Trainable params: 2,163,722
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/10


/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


938/938 - 179s - loss: 0.2545 - accuracy: 0.9162 - 179s/epoch - 191ms/step
Epoch 2/10
938/938 - 172s - loss: 0.0742 - accuracy: 0.9764 - 172s/epoch - 183ms/step
Epoch 3/10
938/938 - 174s - loss: 0.0528 - accuracy: 0.9834 - 174s/epoch - 185ms/step
Epoch 4/10
938/938 - 171s - loss: 0.0410 - accuracy: 0.9871 - 171s/epoch - 182ms/step
Epoch 5/10
938/938 - 173s - loss: 0.0343 - accuracy: 0.9891 - 173s/epoch - 184ms/step
Epoch 6/10
938/938 - 175s - loss: 0.0309 - accuracy: 0.9905 - 175s/epoch - 187ms/step
Epoch 7/10
938/938 - 178s - loss: 0.0242 - accuracy: 0.9924 - 178s/epoch - 190ms/step
Epoch 8/10
938/938 - 174s - loss: 0.0222 - accuracy: 0.9928 - 174s/epoch - 185ms/step
Epoch 9/10
938/938 - 174s - loss: 0.0196 - accuracy: 0.9938 - 174s/epoch - 186ms/step
Epoch 10/10
938/938 - 176s - loss: 0.0190 - accuracy: 0.9938 - 176s/epoch - 188ms/step
157/157 - 5s - loss: 0.0436 - accuracy: 0.9879 - 5s/epoch - 29ms/step


[0.043606992810964584, 0.9879000186920166]